import { useState } from 'react';
import { supabase } from '@/src/lib/supabase';
import { useAuth } from '@/src/contexts/AuthContext';
import { useToast } from '@/src/contexts/ToastContext';
import { Student } from '@/src/types';
import { Loader2 } from 'lucide-react';

interface StudentFormProps {
  student?: Student | null;
  onSuccess: () => void;
  onCancel: () => void;
}

export function StudentForm({ student, onSuccess, onCancel }: StudentFormProps) {
  const { user } = useAuth();
  const { showToast } = useToast();
  const [isSaving, setIsSaving] = useState(false);

  const [formData, setFormData] = useState({
    full_name: student?.full_name || '',
    date_of_birth: student?.date_of_birth || '',
    gender: student?.gender || 'other',
    school_name: student?.school_name || '',
    school_class: student?.school_class || '',
    student_phone: student?.student_phone || '',
    parent_name: student?.parent_name || '',
    parent_phone: student?.parent_phone || '',
    address: student?.address || '',
    enrollment_date: student?.enrollment_date || new Date().toISOString().split('T')[0],
    status: student?.status || 'active',
    note: student?.note || '',
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;
    
    if (!formData.full_name || !formData.parent_phone) {
      showToast('Vui lòng điền họ tên và số điện thoại phụ huynh', 'error');
      return;
    }

    setIsSaving(true);
    
    // Clean up empty strings to null for optional date fields to avoid DB errors
    const payload = {
      ...formData,
      date_of_birth: formData.date_of_birth || null,
      teacher_id: user.id,
    };

    try {
      if (student?.id) {
        // Update
        const { error } = await supabase
          .from('students')
          .update(payload)
          .eq('id', student.id);
          
        if (error) throw error;
        showToast('Cập nhật học sinh thành công', 'success');
      } else {
        // Insert - student_code will be generated by the database trigger
        const { error } = await supabase
          .from('students')
          .insert([payload]);
          
        if (error) throw error;
        showToast('Thêm học sinh mới thành công', 'success');
      }
      onSuccess();
    } catch (error: any) {
      console.error('Error saving student:', error);
      showToast(error.message || 'Có lỗi xảy ra khi lưu học sinh', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="col-span-1 md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Họ tên *</label>
          <input
            type="text"
            name="full_name"
            required
            value={formData.full_name}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="Nguyễn Văn A"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Ngày sinh</label>
          <input
            type="date"
            name="date_of_birth"
            value={formData.date_of_birth}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Giới tính</label>
          <select
            name="gender"
            value={formData.gender}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="male">Nam</option>
            <option value="female">Nữ</option>
            <option value="other">Khác</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Trường học</label>
          <input
            type="text"
            name="school_name"
            value={formData.school_name}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="THPT Trưng Vương"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Lớp chính khóa</label>
          <input
            type="text"
            name="school_class"
            value={formData.school_class}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="10A1"
          />
        </div>

        <div className="col-span-1 md:col-span-2 border-t border-slate-100 pt-4 mt-2">
          <h4 className="text-sm font-semibold text-slate-900 mb-3">Thông tin liên hệ</h4>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Tên phụ huynh</label>
          <input
            type="text"
            name="parent_name"
            value={formData.parent_name}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="Nguyễn Văn B"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Điện thoại phụ huynh *</label>
          <input
            type="tel"
            name="parent_phone"
            required
            value={formData.parent_phone}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="0901234567"
          />
        </div>
        
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Điện thoại học sinh</label>
          <input
            type="tel"
            name="student_phone"
            value={formData.student_phone}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="0909876543"
          />
        </div>

        <div className="col-span-1 md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Địa chỉ</label>
          <input
            type="text"
            name="address"
            value={formData.address}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="123 Lê Lợi, Quận 1"
          />
        </div>

        <div className="col-span-1 md:col-span-2 border-t border-slate-100 pt-4 mt-2">
          <h4 className="text-sm font-semibold text-slate-900 mb-3">Thông tin trung tâm</h4>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Ngày tham gia</label>
          <input
            type="date"
            name="enrollment_date"
            value={formData.enrollment_date}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Trạng thái</label>
          <select
            name="status"
            value={formData.status}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="active">Đang học</option>
            <option value="inactive">Tạm nghỉ</option>
            <option value="archived">Đã nghỉ</option>
          </select>
        </div>

        <div className="col-span-1 md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Ghi chú</label>
          <textarea
            name="note"
            rows={2}
            value={formData.note}
            onChange={handleChange}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="Ghi chú thêm..."
          />
        </div>
      </div>

      <div className="flex justify-end gap-3 pt-5 mt-5 border-t border-slate-100">
        <button
          type="button"
          onClick={onCancel}
          className="px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
        >
          Hủy
        </button>
        <button
          type="submit"
          disabled={isSaving}
          className="flex items-center px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-lg hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-70 transition-colors"
        >
          {isSaving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
          {student ? 'Cập nhật' : 'Thêm mới'}
        </button>
      </div>
    </form>
  );
}
